apiVersion: v1
kind: Secret
metadata:
  name: polaris-persistence-secret
type: Opaque
stringData:
  username: polaris
  password: polaris
  jdbcUrl: jdbc:postgresql://postgres-postgresql:5432/polaris
  # 프로덕션에서는 'polaris-secret'을 안전한 랜덤 문자로 변경필요!!!
  bootstrapCredentials: POLARIS,root,polaris-secret
