apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-add-user-job
  namespace: datahub-hynix
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: psql-client
          image: "bitnamilegacy/postgresql-repmgr:17.6.0-debian-12-r2"
          command:
            - "/bin/sh"
            - "-c"
            - |
              # Using standard SQL string interpolation via psql variables (:NEW_USER and :'NEW_PASSWORD')
              # to prevent SQL injection and avoid leaking passwords in shell process trees.
              psql -h pgpool -p 5432 -U postgres -d airflow \
                -v user="airflow" \
                -v pass="airflow" \
                -c "
                CREATE USER :user WITH PASSWORD :'pass';
                GRANT CONNECT ON DATABASE airflow TO :user;
                GRANT USAGE ON SCHEMA airflow TO :user;
                GRANT SELECT ON ALL TABLES IN SCHEMA airflow TO :user;
                ALTER DEFAULT PRIVILEGES IN SCHEMA airflow GRANT SELECT ON TABLES TO :user;
                "